Feature/plotting training progress
AlexanderVNikitin/tsgm pull request #4
Opened 2022-11-01 19:40 UTC by letiziaia

- *timeGAN*: epochs and checkpoint frequency now defined in .fit(), all training losses are collected during training loops, optional synthetic data generation during .fit(), minor code clean-up
- *visualization*: added function to plot training losses, added option for feature averaging to tsne plots, code formatting (flake8 and black)

2022-11-03 18:25 UTC, AlexanderVNikitin requested changes

2022-11-10 17:18 UTC, letiziaia commented on tsgm/models/timeGAN.py
> +        checkpoints_interval: int = None,
this is done

2022-11-10 17:18 UTC, letiziaia commented on tsgm/models/timeGAN.py
> +        generate_synthetic: list = [],
this is done

2022-11-30 17:56 UTC, AlexanderVNikitin requested changes

2022-11-30 19:50 UTC, letiziaia commented on tsgm/models/timeGAN.py
> +        _losses = np.array([np.array(v) for v in self.values() if isinstance(v, list)])
LossTracker now inherits from python ordered dictionary

2022-11-30 19:50 UTC, letiziaia commented on tsgm/utils/visualization.py
> +    palette=DEFAULT_PALETTE_TSNE,
done

2022-11-30 19:50 UTC, letiziaia commented on tsgm/utils/visualization.py
> +    loss_vector, labels=[], path: str = "/tmp/training_loss.pdf"
now it is empty tuple

2022-12-06 18:02 UTC, merged